### ISSUE TITLE
NYSIIS encoding of 'HANNAH'

### ISSUE THREAD

**Issue by ahood** [howardjp/phonics#14]
Both nysiis_original() and nysiis_modified() are returning 'HANAH'. The encoding rule for a terminal 'H' is ambiguous in this case because of its definition in terms of the preceding and following letters, whereas there is no following letter for the last letter in the name. However it seems more in the spirit of this phonetic encoding to omit the final 'H' (and therefore the second 'A') from the final encoding, and to return 'HAN' instead. The latter interpretation has been adopted in the plurality of implementations [here](https://rosettacode.org/wiki/NYSIIS), by the way.

**Comment by howardjp** [comment]
Corrected latest release.
