### ISSUE TITLE
soundex single characters

### ISSUE THREAD

**Issue by KyleHaynes** [howardjp/phonics#23]
Hi James (Sorry for calling you by you Surname!),

Currently, single character strings return no padded out 0's. Would you consider this a bug?

Looking at three implementations of soundex ...
```R
phonics::soundex("A")
# [1] "A"
RecordLinkage::soundex("A")
# [1] "A000"
stringdist::phonetic("A")
# [1] "A000"
```

It's pretty edge case, but with the types of names I deal with sometimes I get abbreviations, so when doing linkage, if a name was "DA" on one dataset and "D" on another, I might consider it a pair, though blocking on soundex name wouldn't result in a pair ("D" vs "D000").

Happy to do a pull request if you agree.

**Comment by howardjp** [comment]
It is a bug, and one I remember squashing early on.  It seems to have come
back.  There's even a broken test case in the unit testing.

Please, any pull requests welcome :)
