### ISSUE TITLE
Soundex returning single letter instead of augmenting with zeros

### ISSUE THREAD

**Issue by ahood** [howardjp/phonics#38]
If I understand correctly from [the Soundex algorithm steps on Wikipedia](https://en.wikipedia.org/wiki/Soundex#American-Soundex), the encoding of e.g. the string 'A' should be 'A000'. Indeed this is what is produced by other Soundex implementations I'm looking at. However, phonics::soundex('A') returns 'A'. 

Happy to make a pull request if you agree that 'A000' is the correct encoding and if you agree with the rule that "If you have too few letters in your word that you can't assign three numbers, append with zeros until there are three numbers" (quoting from Step 4 in the Wikipedia article).

**Comment by howardjp** [comment]
That's correct, but this is fixed in develop.

**Comment by ahood** [comment]
I see that now, thanks.
